name: Beaumarchais Plays
favicon: null
layout_spectrum: 0.24908
typography_spectrum: 0.7787
title: The Plays of Beaumarchais
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#222220'
    - '#5e5e5e'
    - '#9b8066'
    - '#762e19'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.38252750085666776
  rhythmicContrast: 1
purpose: []
